### PR TITLE
Deploy webhook using ansible

### PR DESCRIPTION
**Pull request by jimallman**
This should install an appropriate webhook to update otindex when a study is saved in the curation app.

### CODE REVIEW

**Comment by jimallman** [comment]
@snacktavish NB - Regarding the amendments webhook, the [old (pre-Pyramid) handler is on branch `before-pyr`](https://github.com/OpenTreeOfLife/phylesystem-api/blob/before-pyr/controllers/search.py#L183), and of course it's [currently failing](https://github.com/OpenTreeOfLife/amendments-0/settings/hooks/8924537?tab=deliveries). More importantly, I don't believe we're currently caching amendments or taxa, so it's moot for now. 

I'll comment this out in the Ansible playbook, but keep the main (study) webhook. I believe this is pointing to the correct (new) URL.

**Comment by jimallman** [comment]
@snacktavish I spoke too soon! It looks like the amendments webhook handler doesn't just clear stale amendments from the cache -- it also [does some processing via `v3/taxonomy/process_additions`](https://github.com/OpenTreeOfLife/phylesystem-api/blob/before-pyr/controllers/search.py#L223-L240). I'll check to see if this method is in the currently deployed code.

EDIT: I found [this old method in taxomachine](https://github.com/OpenTreeOfLife/taxomachine/blob/3326c56e00567aacbe0a84d026e82631a00eb71c/src/main/java/org/opentree/taxonomy/plugins/taxonomy_v3.java#L357-L368). I'm guessing there's a newer implementation that we should call instead..? Or we need to write one.

**Comment by snacktavish** [comment]
Yep - we need to put it into otindex.
I made an issue here:
https://github.com/OpenTreeOfLife/otindex/issues/61


And I pulled the code that was in phylesystem API here:
https://github.com/OpenTreeOfLife/otindex/blob/webhook/otindex/views.py#L338

But haven't had a chance to look at the taxon updates yet. Feel free to take a crack at it if you want!

**Comment by jimallman** [comment]
NB - Managing Github webhooks requires the Ansible user to have [a valid personal access token](https://docs.github.com/en/enterprise-server@3.6/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) on their local filesystem, at `~/.ssh/opentree/OPENTREEAPI_OAUTH_TOKEN`. Or put it anywhere, and update [the `local_api_token_path` variable](https://github.com/OpenTreeOfLife/ot-ansible/blob/c38b4f713f9fd343d363f5f1efcfdb31add8c6c9/roles/phylesystem-api/defaults/main.yml#L19) to match.

**Comment by jimallman** [comment]
These changes are working now on **devtree/devapi**. Ready to merge?

**Pull request merged**
